global:
  scrape_interval: "15s"
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
rule_files:
  - "/home/mtayer/dev/repo/scripts/data/prometheus-rules.yml"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - "localhost:9090"
  - job_name: "rack-example"
    static_configs:
      - targets:
        - "localhost:5000"
  - job_name: "alertmanager"
    static_configs:
      - targets:
        - "localhost:9093"
